config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: "questions#index"

  concern :voted do
    member do
      post :like
      post :dislike
      delete :cancel
    end
  end

  concern :commented do
    member do
      post :comment
    end
  end

  resources :questions, concerns: %i[voted commented] do
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, concerns: %i[voted commented], shallow: true, only: %i[create update destroy] do
      patch :mark_as_best, on: :member
    end
  end

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :rewards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :others, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        get :answers, on: :member
        resources :answers, shallow: true, only: %i[show create update destroy]
      end
    end
  end

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_one :reward, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  belongs_to :user
  belongs_to :best_answer, required: false, class_name: 'Answer', dependent: :destroy, optional: true

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation

  def not_best_answers
    self.answers.where.not(id: self.best_answer_id)
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: %i[show update destroy]

  def index
    @questions = Question.all
    render json: @questions, each_serializer: QuestionsSerializer
  end

  def show
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    authorize @question

    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :bad_request
    end
  end

  def update
    authorize @question

    if @question.update(question_params)
      head :ok
    else
      render json: { errors: @question.errors }, status: :bad_request
    end
  end

  def destroy
    authorize @question

    @question.destroy
    head :no_content
  end

  def answers
    @answers = Question.find(params[:id]).answers
    render json: @answers, each_serializer: AnswersSerializer
  end

  private

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Commented

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show update destroy]
  before_action :authorize_question, only: %i[show update destroy]

  after_action :publish_question, only: %i[create]

  include Voted

  def index
    @questions = Question.all

    authorize @questions
  end

  def show
    @answer = Answer.new
    @answer.links.new
  end

  def new
    @question = Question.new

    @question.links.new
    @question.build_reward
  end

  def create
    @question = current_user.questions.create(question_params)
    authorize @question

    if @question.save
      @question.subscriptions.create(user: current_user)
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: 'Question was successfully deleted'
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body,
                                     files: [],
                                     links_attributes: [:name, :url, :_destroy, :id],
                                     reward_attributes: [:name, :image])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast 'questions',
                                 question: @question.title
  end

  def authorize_question
    authorize @question
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_question.html.slim
.question
  h1= question.title
  p= question.body
  - if question.reward
    .reward
      p= 'Reward is'
      = image_tag(question.reward.image)

  = render 'shared/files', resource: question if question.files.attached?
  = render 'shared/links', links: question.links if question.links.exists?
  = render 'shared/votes', votable: question
  = render 'shared/subscribe', question: question, subscription: question.subscriptions.find_by(user: current_user)
  = render 'shared/comments', commentable: question
  = render 'shared/comment_form', commentable: question

  - if policy(question).edit? && policy(question).destroy?
    = link_to 'Delete question', question_path(question), method: :delete
    | |
    = link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: question.id }

    = form_with model: question, local: false, class: 'hidden', html: { id: "edit-question-#{question.id}" } do |f|
      = f.label :title
      = f.text_field :title

      = f.label :body
      = f.text_area :body

      = f.label :files
      = f.file_field :files, multiple: true

      #links
        = link_to_add_association 'add link', f, :links, partial: 'shared/links_fields'

      = f.submit 'Save'

app/views/questions/_search_item.html.slim
p
  =link_to resource.title, question_path(resource), target: :_blank
  |  by #{resource.user.email}

app/views/questions/index.html.slim
- if @questions.present?
  table class='questions-list'
    thead
      tr
        th Question title
        th Actions
      tbody
        - cache collection_cache_key_for :question do
          - @questions.each do |question|
            tr
              td
                = question.title
              td
                = link_to 'Show', question_path(question)
- else
  .no_questions There are no any questions. Let's create first

- if policy(Question).new?
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, local: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p Links:
  #links
    = f.fields_for :links do |link|
      = render 'shared/links_fields', f: link
    = link_to_add_association 'add link', f, :links, partial: 'shared/links_fields'

  = f.fields_for :reward do |r|
    = r.label :name, 'Reward name'
    = r.text_field :name

    = r.label :image
    = r.file_field :image, accept: 'image/png,image/gif,image/jpeg'

  p
    = f.submit 'Ask'

app/views/questions/show.html.slim
.question-errors
  = render 'shared/errors', resource: @question

- cache @question do
  p Question
  = render @question, question: @question, subscription: @subscription

  .answers
    - if @question.answers.present?
      p Best answer:
      .best-answer
        - if @question.best_answer
          = render @question.best_answer
      .answers-list
        = render @question.not_best_answers
    - else
      .no_answers There are no answers yet.

  p Enter new answer
  .answer-errors
    = render 'shared/errors', resource: @answer

  - if policy(Answer).new?
    = form_with model: [@question, @answer], class: 'new-answer', local: false, data: { type: :json } do |f|
      p
        = f.label :body
        = f.text_area :body

      p
        = f.label :files
        = f.file_field :files, multiple: true

      p Add links:
      #links
        = f.fields_for :links do |link|
          = render 'shared/links_fields', f: link
        = link_to_add_association 'add link', f, :links, partial: 'shared/links_fields'

      = f.submit 'Submit answer'

app/views/questions/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
$('.question').html('<%= j render @question %>');
<% end %>