config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: "questions#index"

  concern :voted do
    member do
      post :like
      post :dislike
      delete :cancel
    end
  end

  concern :commented do
    member do
      post :comment
    end
  end

  resources :questions, concerns: %i[voted commented] do
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, concerns: %i[voted commented], shallow: true, only: %i[create update destroy] do
      patch :mark_as_best, on: :member
    end
  end

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :rewards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :others, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        get :answers, on: :member
        resources :answers, shallow: true, only: %i[show create update destroy]
      end
    end
  end

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_one :reward, dependent: :destroy
  has_one :question_with_best_answer, class_name: 'Question', foreign_key: :best_answer_id, dependent: :nullify
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_create :notify_questions_author

  def mark_as_best!
    question.update(best_answer: self)
    question.reward.update(answer: self) if question.reward
  end

  def best?
    question.best_answer_id == id
  end

  private

  def notify_questions_author
    AnswerNotifyJob.perform_later(self)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, :uid, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true, touch: true
  belongs_to :user

  validates :body, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, http_url: true

  def gist?
    self.url.start_with? 'https://gist.github.com/'
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_one :reward, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  belongs_to :user
  belongs_to :best_answer, required: false, class_name: 'Answer', dependent: :destroy, optional: true

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  validates :title, :body, presence: true

  after_create :calculate_reputation

  def not_best_answers
    self.answers.where.not(id: self.best_answer_id)
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :answer, optional: true

  has_one_attached :image

  validates :name, :image, presence: true
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github, :google_oauth2]

  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  def author_of?(object)
    object.user_id == id
  end

  def rewards
    Reward.where(answer_id: answers)
  end

  def self.find_for_oauth(auth)
    FindForOauth.new(auth).call
  end

  def create_authorization(auth)
    self.authorizations.create(provider: auth.provider, uid: auth.uid)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :value, presence: true, inclusion: [1, -1]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[create]
  before_action :set_answer, only: %i[update destroy mark_as_best]
  before_action :authorize_answer, only: %i[update destroy mark_as_best]

  after_action :publish_answer, only: %i[create]

  include Voted
  include Commented

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = @question

    authorize @answer

    respond_to do |format|
      if @answer.save
        format.json do
          render json: [answer: @answer,
                        links: @answer.links,
                        files: @answer.files.collect { |f| f.filename.to_s }]
        end
      else
        format.json do
          render json: @answer.errors.full_messages,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def update
    authorize @answer
    @question = @answer.question
    @answer.update(answer_params)
  end

  def destroy
    @question = @answer.question
    @answer.destroy
  end

  def mark_as_best
    @answer.mark_as_best!
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :_destroy, :id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast 'answers', answer: @answer.body, user_id: @answer.user_id
    # ActionCable.server.broadcast "answers/#{@answer.question_id}", answer: @answer.body, user_id: @answer.user_id
  end

  def authorize_answer
    authorize @answer
  end
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  before_action :find_attachment
  before_action :get_entity

  def destroy
    authorize @attachment
    @attachment.purge
    redirect_to @url, notice: 'Attachment was successfully deleted'
  end

  private

  def find_attachment
    @attachment = ActiveStorage::Attachment.find(params[:id])
  end

  def get_entity
    @url = @attachment.record.question if @attachment.record.is_a?(Answer)
    @url = @attachment.record if @attachment.record.is_a?(Question)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :find_link, only: %i[destroy]

  def destroy
    authorize @link
    @link.destroy
  end

  private

  def find_link
    @link = Link.find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    set_params
    @result = FulltextSearch.new(@query, @scope, params[:page]).call unless @query.empty?
  end

  private

  def set_params
    @scope = params[:scope] || 'all'
    @query = params[:q].to_s
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def collection_cache_key_for(model)
    klass = model.to_s.capitalize.constantize
    count = klass.count
    max_updated_at = klass.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "#{model.to_s.pluralize}/collection-#{count}-#{max_updated_at}"
  end
end

app/helpers/files_helper.rb
module FilesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThinkneticaQna</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <%= include_gon %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/shared/_comment_form.html.slim
- if policy(commentable).comment?
  = link_to 'Add comment', @comment, class: 'new-comment', data: { commentable_id: commentable.id }

  = form_with scope: :comment, url: polymorphic_path(commentable, action: 'comment'), class: 'hidden',
          html: { id: "new-comment-#{commentable.id}" }, local: false, data: { type: :json } do |f|
    = f.label :body, 'Your comment'
    = f.text_area :body

    = f.submit 'Save comment', class: 'btn btn-info btn-sm'

app/views/shared/_comments.html.slim
div class="comments-#{commentable.id}"
  ul
    - commentable.comments.each do |comment|
      - cache comment do
        li =comment.body

  .comments-errors

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_files.html.slim
div class="files-#{resource.files.first.record_id}"
p Files:
ul
  - resource.files.each do |file|
    li id="file-#{file.id}"
      = link_to file.filename.to_s, url_for(file)

      - if policy(resource).destroy?
        = link_to 'Delete attachment', file_path(file.id), method: :delete

app/views/shared/_flash_js.js.erb
$('.flashes').empty();
$('.flashes').replaceWith('<%= render partial: 'shared/flashes', locals: { flash: flash } %>');

app/views/shared/_flashes.html.slim
.flashes
  - flash.each do |key, value|
    p= value

app/views/shared/_links.html.slim
div class="links-#{links.first.linkable.id}"
  p Links:
  ul
    - links.each do |link|
      - if link.gist?
        <script src="#{link.url}.js"></script>
      - else
        li= link_to link.name, link.url

      - if current_user&.author_of?(link.linkable)
        = link_to 'Delete link', link_path(link), remote: true, method: :delete

app/views/shared/_links_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name

  .field
    = f.label :url
    = f.text_field :url

  = link_to_remove_association 'remove link', f

app/views/shared/_navigation.html.slim
div
  h2 Welcome #{current_user&.email}
  - if user_signed_in?
    = link_to 'LogOut', destroy_user_session_path, method: :delete
    | |
    = link_to 'Questions', questions_path
    | |
    = link_to 'Rewards', rewards_path
  - else
    = link_to 'Registration', new_user_registration_path
    | |
    = link_to 'Login', new_user_session_path

app/views/shared/_subscribe.html.slim
.subscription
  - if current_user
    - if subscription.nil? || policy(subscription).create?
      = link_to 'Subscribe to new answers', question_subscriptions_path(question), method: :post, remote: true,
              data: { type: :js }, class: 'subscribe-button'

    - if !subscription.nil? && policy(subscription).destroy?
      = link_to 'Unsubscribe', subscription_path(subscription), method: :delete, remote: true,
              data: { type: :js }, class: 'unsubscribe-button'

app/views/shared/_votes.html.slim
div class="votes-#{votable.id}"
  p class='votes' Votes: #{votable.rating || 0}
  - if policy(votable).like?
    .vote
      = link_to 'Like', polymorphic_path(votable, action: :like), method: :post, remote: true,
              data: { type: :json }, class: (policy(votable).like? ? 'like-button' : 'like-button hidden')
      = link_to 'Dislike', polymorphic_path(votable, action: :dislike), method: :post, remote: true,
              data: { type: :json }, class: (policy(votable).dislike? ? 'dislike-button' : 'dislike-button hidden')
      = link_to 'Cancel', polymorphic_path(votable, action: :cancel), method: :delete, remote: true,
              data: { type: :json }, class: (policy(votable).cancel? ? 'cancel-button' : 'cancel-button hidden')