config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
    mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: "questions#index"

  concern :voted do
    member do
      post :like
      post :dislike
      delete :cancel
    end
  end

  concern :commented do
    member do
      post :comment
    end
  end

  resources :questions, concerns: %i[voted commented] do
    resources :subscriptions, shallow: true, only: %i[create destroy]
    resources :answers, concerns: %i[voted commented], shallow: true, only: %i[create update destroy] do
      patch :mark_as_best, on: :member
    end
  end

  resources :files, only: %i[destroy]
  resources :links, only: %i[destroy]
  resources :rewards, only: %i[index]

  namespace :api do
    namespace :v1 do
      resource :profiles, only: [] do
        get :me, on: :collection
        get :others, on: :collection
      end
      resources :questions, only: %i[index show create update destroy] do
        get :answers, on: :member
        resources :answers, shallow: true, only: %i[show create update destroy]
      end
    end
  end

  get '/search', to: 'search#search'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question, touch: true
  belongs_to :user
  has_one :reward, dependent: :destroy
  has_one :question_with_best_answer, class_name: 'Question', foreign_key: :best_answer_id, dependent: :nullify
  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  after_create :notify_questions_author

  def mark_as_best!
    question.update(best_answer: self)
    question.reward.update(answer: self) if question.reward
  end

  def best?
    question.best_answer_id == id
  end

  private

  def notify_questions_author
    AnswerNotifyJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[create]
  before_action :set_answer, only: %i[update destroy mark_as_best]
  before_action :authorize_answer, only: %i[update destroy mark_as_best]

  after_action :publish_answer, only: %i[create]

  include Voted
  include Commented

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = @question

    authorize @answer

    respond_to do |format|
      if @answer.save
        format.json do
          render json: [answer: @answer,
                        links: @answer.links,
                        files: @answer.files.collect { |f| f.filename.to_s }]
        end
      else
        format.json do
          render json: @answer.errors.full_messages,
                 status: :unprocessable_entity
        end
      end
    end
  end

  def update
    authorize @answer
    @question = @answer.question
    @answer.update(answer_params)
  end

  def destroy
    @question = @answer.question
    @answer.destroy
  end

  def mark_as_best
    @answer.mark_as_best!
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :_destroy, :id])
  end

  def set_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast 'answers', answer: @answer.body, user_id: @answer.user_id
    # ActionCable.server.broadcast "answers/#{@answer.question_id}", answer: @answer.body, user_id: @answer.user_id
  end

  def authorize_answer
    authorize @answer
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question, only: %i[create]
  before_action :set_answer, only: %i[update destroy]

  def show
    @answer = Answer.find(params[:id])
    render json: @answer
  end

  def create
    @answer = current_user.answers.new(answer_params)
    @answer.question = @question

    authorize @answer

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize @answer

    if @answer.update(answer_params)
      # head :ok
      @answer
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @answer

    @answer.destroy
    # head :no_content
    @answer
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  .answer*{ data: { answer_id: answer.id } }
    p= answer.body

    = render 'shared/links', links: answer.links if answer.links.exists?
    = render 'shared/files', resource: answer if answer.files.attached?
    = render 'shared/votes', votable: answer
    = render 'shared/comments', commentable: answer
    = render 'shared/comment_form', commentable: answer

    - if policy(answer).update?
      = link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
      = link_to 'Delete answer', answer_path(answer), remote: true, class: 'delete-answer-link', data: { answer_id: answer.id }, method: :delete

      = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
        = f.label :body, 'Your answer'
        = f.text_area :body

        = f.label :files
        = f.file_field :files, multiple: true

        #links
          = link_to_add_association 'add link', f, :links, partial: 'shared/links_fields'

        = f.submit 'Save'

    - if policy(answer).mark_as_best?
      = link_to 'Mark as best', mark_as_best_answer_path(answer), remote: true, class: 'mark-as-best-answer-link', data: { answer_id: answer.id }, method: :patch

app/views/answers/_best_answer.html.slim
.answer*{data: { answer_id: answer.id } }
  p= answer.body

  = render 'shared/files', resource: answer if answer.files.attached?
  = render 'shared/links', links: answer.links if answer.links.exists?

  - if policy(answer).update?
    = link_to 'Edit answer', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    = link_to 'Delete answer', answer_path(answer), remote: true, class: 'delete-answer-link', data: { answer_id: answer.id }, method: :delete

    = form_with model: answer, local: false, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      = f.label :body, 'Your answer'
      = f.text_area :body

      = f.label :files
      = f.file_field :files, multiple: true

      #links
        = link_to_add_association 'add link', f, :links, partial: 'shared/links_fields'

      = f.submit 'Save'

app/views/answers/_search_item.html.slim
p
  | '#{resource.body}'
  |  mentioned in
  =link_to resource.question.title, question_path(resource.question.id), target: :_blank
  |  by #{resource.user.email}

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
if ($('.no_answers')) $('.no_answers').remove();
$('.answers').append('<%= j render @answer %>');
$('.new-answer #answer_body').val('');
$('.new-answer').find('input').each(function() {
    $(this).val('');
});
<% end %>

app/views/answers/destroy.js.erb
<% unless @answer.persisted? %>
$('div.answer[data-answer_id="<%= @answer.id %>"]').remove();
<% end %>

app/views/answers/mark_as_best.js.erb
$('.best-answer').html('<%= j render 'answers/best_answer', answer: @answer.question.best_answer %>');
$('.answers-list').html('<%= render @answer.question.not_best_answers %>');

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
$('div.answer[data-answer_id="<%= @answer.id %>"]').html('<%= j render @answer %>');
<% end %>